protected/models/Payment.php
<?php
Class Payment Extends CActiveRecord {
	const ANNUALY = 'annualy';
	const QUARTERLY = 'quarterly';

	const Done = 'Done';
	const Pending = 'Pending';
	const Failed = 'Failed';

	protected $_period;

	public static function model($method = __CLASS__) {
		if($method == __CLASS__)
			return parent::model(__CLASS__);
		else
			return parent::model($method.'Payment');
	}

	public function init() {
		$this->method = $this->getMethod();
	}

	public function tableName() {
		return 'payment';
	}

	public function rules() {
		return Array(
			Array('member, amount, date', 'required', 'on' => 'create'),
			Array('member, amount, status, method', 'safe', 'on' => 'create'),
		);
	}

	public static function getMethods() {
		return Array(New StandardPaypalPayment, New DirectTransferPayment, New DirectDebitAuthorizationPayment);
	}

	public static function getPeriods() {
		return array(
			self::ANNUALY => Yii::t('payment', 'Annualy'),
			self::QUARTERLY => Yii::t('payment', 'Quarterly'),
		);
	}

	public function getMethod() {
		return str_replace('Payment', Null, get_class($this)); // if class name if FooPayment, return Foo.
	}

	public function getStatuses() {
		return Array(
			self::Done => Yii::t('payment', 'Done'),
			self::Pending => Yii::t('payment', 'Pending'),
			self::Failed => Yii::t('payment', 'Failed')
		);
	}

	public function pay($redirectUrl) {
		return False;
	}

	public function getTitle() {
		return False;
	}

	public function relations() {
		return array(
			'owner' => array(self::BELONGS_TO, 'Member', 'member')
		);
	}

	public function instantiate($attributes) {
		$method = $attributes['method'];
		$name = $method.'Payment';
		return New $name(null);
	}

	public function getFormattedDate() {
		if($this->date)
			return Yii::app()->format->formatDate($this->date);
	}

	public function setPeriod($period) {
		$this->_period = (Int)$period;
	}

	public function getPeriod() {
		return $this->_period;
	}

	public function getCouldAutomaticallyUpdate() {
		return False;
	}

	public function getMethodTitle() {
		foreach(self::getMethods() as $method)
			if($method->getMethod() == $this->getMethod())
				return $method->title;
	}

	public function save($runValidations = True, $attributes=Null) {
		if(!$this->status)
			$this->status = self::Done;

		if(!$this->method)
			$this->setAttribute('method', $this->getMethod());
		return parent::save($runValidations, $attributes);
	}
}

Class DirectDebitAuthorizationPayment Extends Payment {
	public function getTitle() {
		return Yii::t('payment', 'Direct Debit Authorization (Germany only)');
	}

	public function pay($redirectUrl) {
		Yii::import('ext.yii-mail.*');
		$mail = New YiiMailMessage;
		$mail->subject = Yii::t('join', 'Your payment for Join The Game campaign');
		$mail->from = 'jointhegame-admin@kde.org';
		$mail->to = array($this->owner->email);
		$mail->body = Yii::app()->controller->renderPartial('/mail/direct_debit', array('model' => $this->owner), True, True);
		Yii::app()->mail->send($mail);

		$this->status = self::Pending;
		$this->save();
		Yii::app()->controller->redirect($redirectUrl);
	}
}

Class DirectTransferPayment Extends Payment {
	public function getTitle() {
		return Yii::t('payment', 'Direct Transfer (Manual)');
	}

	public function pay($redirectUrl) {
		Yii::import('ext.yii-mail.*');
		$mail = New YiiMailMessage;
		$mail->subject = Yii::t('join', 'Your payment for Join The Game campaign');
		$mail->from = 'jointhegame-admin@kde.org';
		$mail->to = array($this->owner->email);
		$mail->body = Yii::app()->controller->renderPartial('/mail/direct_transfer', array('model' => $this->owner), True, True);
		Yii::app()->mail->send($mail);

		$this->status = self::Pending;
		$this->save();
		Yii::app()->controller->redirect($redirectUrl);
	}
}

Class ManualPaypalPayment Extends Payment {
	public function getTitle() {
		return Yii::t('payment', 'Paypal (manual)');
	}

	public function pay($redirectUrl) {
		Yii::import('ext.yii-mail.*');
		$mail = New YiiMailMessage;
		$mail->subject = Yii::t('join', 'Your payment for Join The Game campaign');
		$mail->from = 'jointhegame-admin@kde.org';
		$mail->to = array($this->owner->email);
		$mail->body = Yii::app()->controller->renderPartial('/mail/paypal_manual', array('model' => $this->owner), True, True);
		Yii::app()->mail->send($mail);

		$this->status = self::Pending;
		$this->save();
		Yii::app()->controller->redirect($redirectUrl);
	}
}

Class StandardPaypalPayment Extends Payment {
	const Verified = 'VERIFIED';
	const Completed = 'Completed';

	public function getTitle() {
		return Yii::t('payment', 'Paypal (instant, recommended)');
	}

	public function pay($redirectUrl) {
		Yii::app()->controller->render('/payment/paypal/standard/button', array(
			'model' => $this,
			'redirectUrl' => $redirectUrl
		));
	}

	public function saveAutomatically($data) {
		if($data['txn_type'] != 'web_accept')
			return False;

		$data['cmd'] = '_notify-validate';

		$config=new CConfiguration(Yii::getPathOfAlias('application.config').'/paypal.php');
		$curl = curl_init( $config['url'] );

		curl_setopt( $curl, CURLOPT_RETURNTRANSFER, True );
		curl_setopt( $curl, CURLOPT_FOLLOWLOCATION, True );
		curl_setopt( $curl, CURLOPT_POST, True );
		curl_setopt( $curl, CURLOPT_POSTFIELDS, $data );

		$response = curl_exec( $curl );

		$this->transaction = $data['txn_id'];
		$this->member = $data['custom'];
		$this->date = strtotime($data['payment_date']);
		$this->amount = $data['mc_gross'];

		if($response == self::Verified) {
			Switch ($data['payment_status']) {
				case self::Completed:
					$this->status = self::Done;
				break;

				case self::Pending:
					$this->status = self::Pending;
				break;

				case self::Failed:
					$this->status = self::Failed;
				break;
			}
		} else
			$this->status = self::Failed;

		$this->save(False);
	}
}

protected/controllers/PaymentController.php
<?php
Class PaymentController Extends Controller {
	public function accessRules() {
		return Array(
			array(
				'allow',
				'actions' => array('admin', 'create', 'update', 'delete', 'estimate'),
				'roles' => array('admin')
			),

			array(
				'deny'
			)
		);
	}

	public function actionAdmin() {
		$dataProvider = New CActiveDataProvider('Payment');
		if($_GET['member'])
			$dataProvider->criteria->condition = 'member = '.$_GET['member'];

		$this->render('admin', array('dataProvider' => $dataProvider));
	}

	public function actionCreate() {
		$model = New Payment;
		$model->scenario = 'create';

		if($_POST['Payment']) {
			$model->attributes = $_POST['Payment'];
			$model->date = CDateTimeParser::parse($_POST['Payment']['formattedDate']);

			if($model->validate()) {
				$name = $_POST['Payment']['method'].'Payment';
				$model = New $name;
				$model->scenario = 'create';
				$model->attributes = $_POST['Payment'];
				$model->date = strtotime($_POST['Payment']['formattedDate']);

				if($model->save())
					$this->redirect(Controller::createUrl('/payment/admin'));
			}
		}

		$this->render('create', array('model' => $model));
	}

	public function actionUpdate() {
		$model = Payment::model()->findbyPK($_GET['id']);
		$model->scenario = 'create';

		if($_POST[get_class($model)]) {
			if($_POST['automaticUpdate'])
				$model->automaticUpdate();
			else {
				$model->attributes = $_POST[get_class($model)];
				$model->date = strtotime($_POST[get_class($model)]['formattedDate']);
				$model->save();
			}
		}

		$this->render('create', array('model' => $model));
	}

	public function actionDelete() {
		$payment = Payment::model()->findByPK($_GET['id']);
		$payment->delete();
	}

	public function actionEstimate() {
		if($_GET['from'] && $_GET['to']) {
			$members = Member::model()->findAll(Array(
				'condition' => 'number > 0'
			));
		} else
			$members = Array();

		$this->render('estimate', Array('members' => $members, 'from' => $_GET['from'], 'to' => $_GET['to']));
	}
}

protected/views/payment/SumColumn.php
<?php
Yii::import('zii.widgets.grid.CDataColumn');

Class SumColumn Extends CDataColumn {
	public $name = 'amount';
	public $doneSum = 0;
	public $allSum = 0;

	public function getHasFooter() {
		return True;
	}

	public function renderDataCellContent($row, $data) {
		$amount = $data->{$this->name};
		echo $amount;
		$this->allSum += (float)$amount;
		if($data->status == Payment::Done)
			$this->doneSum += $amount;
	}

	public function renderFooterCellContent() {
		echo Yii::t('payment', 'Total: :done/:all', array(':done' => $this->doneSum, ':all' => $this->allSum));
	}
}

protected/views/payment/_payments.php
<?php
$dataProvider->pagination = False;

if(!$columns) {
	$columns = Array(
		'id',
		'owner.fullName',
		'date:date',
		'methodTitle',
		'status',
		array(
			'class' => 'SumColumn'
		),
	);
}

if(Member::model()->findByPk(Yii::app()->user->id)->isAdmin) {
	$columns[] = array(
		'class' => 'CButtonColumn',
		'template' => '{update}{delete}'
	);
}

Yii::import('application.views.payment.SumColumn');
$this->widget('zii.widgets.grid.CGridView', array(
	'cssFile' => False,
	'dataProvider' => $dataProvider,
	'rowCssClassExpression' => '$data->status',
	'columns' => $columns
));

protected/views/payment/admin.php
<a href="<?php echo Controller::createUrl('/payment/create');?>">
	<?php echo Yii::t('payment', 'Add new payment');?>
</a>
<br />
<a href="<?php echo Controller::createUrl('/paypal/recurringprofiles');?>">
	<?php echo Yii::t('payment', 'View all automatic payments');?>
</a>
<br />
<a href="<?php echo Controller::createUrl('/payment/estimate');?>">
	<?php echo Yii::t('payment', 'Estimate payments');?>
</a>
<hr />
<br />

<?php
$this->renderPartial('_payments', array('dataProvider' => $dataProvider));
?>

protected/views/payment/create.php
<?php $form = $this->beginWidget('CActiveForm'); ?>

	<?php
		$this->extra = CHtml::errorSummary($model);
	?>

	<div class="row">
		<?php echo $form->labelEx($model, 'member'); ?>
		<br />
		<?php
// 		var_dump($model->member, $model->owner);
		$this->widget('zii.widgets.jui.CJuiAutoComplete', array(
			'name'=>'member_label',
			'value' => $model->owner ? $model->owner->fullName.' ('.$model->owner->email.')' : '',
			'sourceUrl'=>Yii::app()->createUrl('/member/search'),
			'options' => Array(
				'select' => 'js:function(event, ui) {
					$("#payment_member").val(ui.item.id);
				}'
			)
		));
		?>
		<?php echo $form->hiddenField($model, 'member', array('id' => 'payment_member')); ?>
		<br />
		<?php echo $form->error($model, 'member'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model, 'amount'); ?>
		<br />
		<?php echo $form->textField($model, 'amount'); ?>
		<br />
		<?php echo $form->error($model, 'amount'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model, 'date'); ?>
		<br />
		<?php $this->widget('zii.widgets.jui.CJuiDatePicker', Array(
			'model' => $model,
			'attribute' => 'formattedDate'
		)); ?>
		<br />
		<?php echo $form->error($model, 'formattedDate'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model, 'method'); ?>
		<br />
		<?php echo $form->dropDownList($model, 'method', CHtml::listData($model->methods, 'method', 'title')); ?>
		<br />
		<?php echo $form->error($model, 'method'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model, 'status'); ?>
		<br />
		<?php echo $form->dropDownList($model, 'status', $model->statuses); ?>
		<br />
		<?php echo $form->error($model, 'status'); ?>
	</div>

	<div class="row">
		<?php
			echo CHtml::submitButton();
			if(!$model->isNewRecord && $model->couldAutomaticallyUpdate)
				echo CHtml::submitButton(Yii::t('payment', 'Sync'), array('name' => 'automaticUpdate'));
		?>
	</div>
<?php $this->endWidget(); ?>

protected/views/payment/estimate.php
<?php
$this->beginWidget('CActiveForm', array('method' => 'get'));

	echo CHtml::label(Yii::t('payment', 'From'), 'from').'&nbsp';
	echo '<br />';
	$this->widget('zii.widgets.jui.CJuiDatePicker', Array(
		'id' => 'from',
		'name' => 'from',
		'value' => $from
	));

	echo '<br />';

	echo CHtml::label(Yii::t('payment', 'To'), 'to');
	echo '<br />';
	$this->widget('zii.widgets.jui.CJuiDatePicker', Array(
		'id' => 'to',
		'name' => 'to',
		'value' => $to
	));

	echo '<br /><br />';

	echo CHtml::submitButton();
$this->endWidget();

if($members) {
	$total = 0;
	$expectedToPay = Array();

	foreach($members as $member) {
		if(($member->nextPaymentDate > strtotime($from)) && ($member->nextPaymentDate < strtotime($to))) {
			$total += $member->lastPaymentAmount;
			$expectedToPay[] = $member;
		}
	}

	echo '<br /><h1>'.Yii::t('payment', 'We estimate :amount euros to be payed from :from to :to. Below, is a detailed list of expected payments.', Array(
		':amount' => Yii::app()->format->formatNumber($total),
		':from' => Yii::app()->format->formatDate(strtotime($from)),
		':to' => Yii::app()->format->formatDate(strtotime($to))
	)).'</h1><br />';

	if(!$columns) {
		$columns = Array(
			'number:number:'.Yii::t('payment', 'Number'),
			'fullName:raw:'.Yii::t('payment', 'Full Name'),
			'nextPaymentDate:date:'.Yii::t('payment', 'Expected payment date'),
			'lastPaymentAmount:number:'.Yii::t('payment', 'Expected payment amount')
		);
	}

	$this->widget('zii.widgets.grid.CGridView', array(
		'cssFile' => False,
		'dataProvider' => New CArrayDataProvider($expectedToPay, Array(
			'pagination' => False,
			'sort' => Array(
				'attributes' => array('fullName', 'nextPaymentDate', 'lastPaymentAmount'),
				'defaultOrder' => 'nextPaymentDate'
			)

		)),
		'columns' => $columns
	));
}